#!/usr/bin/env bash
# A Bash script that displays all running processes in a user-friendly, hierarchical format

ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,lstart,time,command --forest | awk 'NR==1{$6="STARTED"}1'
