#!/usr/bin/env bash
# A Bash script that handles SIGTERM and keeps running

trap_handler() {
  echo "I am invincible!!!"
}

trap trap_handler SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
